spring:
  application:
    name: tracking-number-service # Your application's name
  data:
    mongodb:
      uri: ${MONGODB_BASE_URI}&maxPoolSize=${MONGO_MAX_POOL_SIZE}&minPoolSize=${MONGO_MIN_POOL_SIZE}
      auto-index-creation: false

server:
  port: 8080 # The port on which your Spring Boot application will listen for incoming requests
  tomcat:
    threads:
      min-spare: 2
      max: 10
    accept-count: 100
    max-connections: 50

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

logging:
  level:
    root: INFO
    com.learning.trackingnumber_service: INFO


